# This fanning in of the results of a loop uses emptyDir in order to avoid
# "collisions" of the looping steps outputs. Notice that 
#  - no persisted volume is here required. 
#  - this version of the write-some-result is much simpler than the one of 
#    example-loop-faning-in-results-as-list.yml 
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameters-
spec:
  entrypoint: main

  templates:
  - name: main
    steps:
    - - name: loop-write-some-result
        template: write-some-result
        arguments:
          parameters:
          - name: some-file-content
            value: "{{item}}"
        withItems: 
          - "one"
          - "two"
          - "three"

    - - name: print-loop-result
        templateRef:
          name: workflow-template-utils-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
          - name: message
            # This whale should say:
            #         ________________________ 
            #         < ["one","two","three"] >
            #         ------------------------ 
            value: "{{steps.loop-write-some-result.outputs.parameters.results-values}}"
            
  - name: write-some-result
    inputs:
      parameters:
      - name: some-file-content
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        with open("results.txt", "a+") as f:
          f.write("{{inputs.parameters.some-file-content}}" + "\n")
      volumeMounts:
       - name: out
         mountPath: /mnt/out
    volumes:
        - name: out
          emptyDir: { }
    outputs:
      parameters:
      - name: results-values
        valueFrom:
          path: "results.txt"

