# With some inspiration taken in
#   https://github.com/argoproj/argo-workflows/blob/master/examples/loops-param-result.yaml
# or
#   https://github.com/argoproj/argo-workflows/blob/master/examples/parameter-aggregation-dag.yaml
# this workflow tries to aggregate the results at the level of the workflow.
# But it seems that the usage of the expression 
#     "{{steps.loop-write-some-result.outputs.result}}"
# is not possible.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameters-
spec:
  entrypoint: main
  volumes:
  - name: workdir
    hostPath:
      path: /data/host
  arguments:
    parameters:
    - name: persistedVolume   
      value: /data/host

  templates:
  - name: main
    steps:    
    - - name: loop-write-some-result
        template: write-some-result
        arguments:
          parameters:
          - name: some-file-content
            value: "{{item}}"
        withItems: 
          - "one"
          - "two"
          - "three"

    - - name: print-loop-results
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "{{steps.loop-write-some-result.outputs.parameters.results-values}}"
            
  - name: write-some-result
    inputs:
      parameters:
      - name: some-file-content
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import os
        output_filename=os.path.join("{{workflow.parameters.persistedVolume}}",
                                     "results.txt")
        with open(output_filename, "a+") as f:
          f.write("{{inputs.parameters.some-file-content}}" + "\n")
      volumeMounts:
       - name: workdir
         mountPath: /data/host
    outputs:
      parameters:
      - name: results-values
        valueFrom:
          path: "{{workflow.parameters.persistedVolume}}/results.txt"

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]