# With some inspiration taken in
#   https://github.com/argoproj/argo-workflows/blob/master/examples/loops-param-result.yaml
# or
#   https://github.com/argoproj/argo-workflows/blob/master/examples/parameter-aggregation-dag.yaml
# this workflow aggregates the results at the level of the workflow.
# Refer to the comments of the write-some-result template.
#
# Warning: because this workflow creates a `results.txt` in the persisted
# volume, it is not re-entrant. In other terms, before running this workflow
# make sure that are no previously exising `results.txt` file.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameters-
spec:
  entrypoint: main
  volumes:
  - name: workdir
    hostPath:
      path: /data/host
  arguments:
    parameters:
    - name: persistedVolume   
      value: /within-container-mount-point/

  templates:
  - name: main
    steps:
    - - name: loop-write-some-result
        template: write-some-result
        arguments:
          parameters:
          - name: some-file-content
            value: "{{item}}"
        withItems: 
          - "one"
          - "two"
          - "three"

    - - name: print-loop-result
        templateRef:
          name: workflow-template-utils-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
          - name: message
            # This whale should say (unless you had a pre-existing results.txt
            # file in the persisted volume):
            #         ________________________ 
            #         < ["one","two","three"] >
            #         ------------------------ 
            value: "{{steps.loop-write-some-result.outputs.parameters.results-values}}"
            
  - name: write-some-result
    inputs:
      parameters:
      - name: some-file-content
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import os
        ###############################
        #####      READ HERE     ######
        ###############################
        # We here need a temporary name that
        #  - will also be the "path" valueFrom of the outputs. It can thus
        #    only use workflow variables (since "path" uses workflow variable
        #    values)
        #  - is sufficiently unique to avoid collisions with other loop 
        #    instances. 
        # In addition we CANNOT use a (workflow) generated identifier because
        #  - the calling loop step can NOT use expressions like
        #    {steps.loop-write-some-result.id} to pass them as input parameter
        #    to this template (refer to "step-identifier-access-issue.yml" issue
        #    workflow)
        #  - templates (among which this template) do NOT have an ".id" variable
        #    (refer to https://argoproj.github.io/argo-workflows/variables/ )
        # This means we don't have much choice and have to accept that the
        # some-file-content input parameter is indeed an indentifier. Which is
        # a quite strong assumption 
        output_filename=os.path.join(
          "{{workflow.parameters.persistedVolume}}",
          "{{inputs.parameters.some-file-content}}"+"-results.txt")
        with open(output_filename, "a+") as f:
          f.write("{{inputs.parameters.some-file-content}}" + "\n")
      volumeMounts:
       - name: workdir
         mountPath: "{{workflow.parameters.persistedVolume}}"
    outputs:
      parameters:
      - name: results-values
        valueFrom:
          path: "{{workflow.parameters.persistedVolume}}/{{inputs.parameters.some-file-content}}-results.txt"

