# Refer to the lenghty comment section within
#   write-some-result.script.source 
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameters-
spec:
  entrypoint: main
  volumes:
  - name: workdir
    hostPath:
      path: /data/host
  arguments:
    parameters:
    - name: namewithoutdash   
      value:  '{"scalar": "10"}'

  templates:
  - name: main
    steps:
    - - name: without-dash
        template: whalesay
        arguments:
          parameters:
          - name: message
            # Applying jsonpath to a parameter name that does NOT use a dash
            # if effective a illustrated by the whale that as expected says
            #      ____ 
            #     < 10 >
            #      ---- 
            value: "{{=jsonpath(workflow.parameters.namewithoutdash, '$.scalar')}}"
            
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]