# This is a copy of
# https://github.com/argoproj/argo-workflows/blob/master/examples/configmaps/simple-parameters-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-parameters
  labels:
    # Note that this label is required for the informer to detect this ConfigMap.
    workflows.argoproj.io/configmap-type: Parameter
data:
  msg: 'hello world'
