# output_dir = 'junk'
# vintages = [2009, 2012, 2015]
# city = 'LYON'
# boroughs = [
#             'LYON_1ER',
#             'LYON_2EME',
#             'LYON_3EME',
#             'LYON_4EME',
#             'LYON_5EME',
#             'LYON_6EME',
#             'LYON_7EME',
#             'LYON_8EME',
#             'LYON_9EME'
# ]
# databases = {
#     2009: {
#         'PG_HOST': '192.168.1.51',
#         'PG_PORT': '5432',
#         'PG_NAME': 'citydb-full_lyon-2009',
#         'PG_USER': 'postgres',
#         'PG_PASSWORD': 'postgres'
#     },
#     2012: {
#         'PG_HOST': '192.168.1.51',
#         'PG_PORT': '5433',
#         'PG_NAME': 'citydb-full_lyon-2012',
#         'PG_USER': 'postgres',
#         'PG_PASSWORD': 'postgres'
#     },
#     2015: {
#         'PG_HOST': '192.168.1.51',
#         'PG_PORT': '5434',
#         'PG_NAME': 'citydb-full_lyon-2015',
#         'PG_USER': 'postgres',
#         'PG_PASSWORD': 'postgres'
#     }
# }
# FIXME: this is a debug config that should be erased later on
output_dir = 'junk'
vintages = [2009, 2012, 2015]
city = 'LYON'
boroughs = [
            'LYON_1ER',
            'LYON_2EME',
            'LYON_3EME',
            'LYON_4EME',
            'LYON_5EME',
            'LYON_6EME',
            'LYON_7EME'
]
# FIXME: Currently, these files needs to be copied created manually and
#  stored in Docker/CityTiler-DockerContext since they are copied by the
#  DockerFile in the docker context and handed to the tiler. However,
#  the content of these files is the same as the configuration of the
#  databases object defined below. In the future, these files may be
#  generated by the docker_temporal_tile and from the databases object below
#  with Jinja2.
db_config_files = ['CityTilerDBConfig2009.yml', 'CityTilerDBConfig2012.yml']
databases = {
    2009: {
        'PG_HOST': '192.168.1.51',
        'PG_PORT': '5432',
        'PG_NAME': 'citydb-full_lyon-2009',
        'PG_USER': 'postgres',
        'PG_PASSWORD': 'postgres'
    },
    2012: {
        'PG_HOST': '192.168.1.51',
        'PG_PORT': '5433',
        'PG_NAME': 'citydb-full_lyon-2012',
        'PG_USER': 'postgres',
        'PG_PASSWORD': 'postgres'
    }
}
