apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameters-
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: collect-lyon-data
  arguments:
    parameters:
    # To override the configuration value, run `argo submit` with the -p option:
    # argo submit parameter.yaml -p config="`cat <path-to-config-file>`"
    - name: config
      value: dummy config value
    - name: pattern
      value: BATI
    - name: results_dir
      value: stage_1

  templates:
  - name: collect-lyon-data
    inputs:
      parameters:
      - name: config       # parameter declaration
    container:
      # FIXME run cowsay with that message input parameter as args
      image: vcity:collect_lyon_data
      imagePullPolicy: Never
      # command: []
      args: ["python3", "./entrypoint.py", "{{inputs.parameters.config}}"]

