apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameters-
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: collect-lyon-data
  arguments:
    parameters:
    - name: message
      value: hello world

  templates:
  - name: collect-lyon-data
    inputs:
      parameters:
      - name: message       # parameter declaration
    container:
      # FIXME run cowsay with that message input parameter as args
      image: vcity:collect_lyon_data
      imagePullPolicy: Never
      # command: []
      args: ["python3", "./entrypoint.py", "{{inputs.parameters.message}}"]

